Phoneme codes
Ballena0/backend-pi-gpi pull request #11
Opened 2021-06-30 04:08 UTC by SebaPerezBerrios

# Description

Se incluye funcion dentro del modulo de traducción para obtener tanto la lista de fonemas en código IPA como también el string en UTF-8 que idealmente va a ser mostrado al usuario.

Ejemplo lista de fonemas: ['P', 'AA1', 'P', 'Y', 'AH0', 'L', 'ER0', ' ', 'P', 'EH1', 'T', 'S', ' ', ',', ' ', 'F', 'AO1', 'R', ' ', 'IH0', 'G', 'Z', 'AE1', 'M', 'P', 'AH0', 'L', ' ', 'K', 'AE1', 'T', 'S', ' ', 'AH0', 'N', 'D', ' ', 'D', 'AA1', 'G', 'Z']

Con esto es posible obtener los audios de estos fonemas y recrear una frase con audio

Ejemplo string de fonemas: "hɛˈloʊ"

## Type of change

- [ ] Bug fix 
- [x] New feature 
- [ ] Breaking change (cambio que puede romper la aplicación)
- [ ] Docs

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

2021-07-04 23:00 UTC, mapacheverdugo approved these changes
Ojo, subiste los cambios con un commit de la @mariam6697 que no estaba mergeado, ni si quiera había abierto un PR. Para que tengas cuidado a la próxima

Ahora, comentando ambos commits, me funcionaron super bien los dos. Dejé un par de comentarios de detallitos para ver si les parece pertinente ono

2021-07-05 00:47 UTC, Ballena0 commented on apps/translate/interface.py
> +def translate_text(text, src_language, dest_language):
Me parece excelente idea, deberian quedar keyworded `def translate_text(src_language="es", dest_language="en", text):` . De igual manera debe realizarse en el PR de esa rama.

2021-07-05 00:50 UTC, Ballena0 commented
Exactamente como dijo @mapacheverdugo se necesita que la rama base de este PR sea `dev` por que es necesario que todas las funcionalidades queden documentadas por separado. La explicación está bien. @SebaPerezBerrios

2021-07-05 00:50 UTC, Ballena0 requested changes
En base a lo comentado anteriormente.

2021-07-15 18:02 UTC, mapacheverdugo commented
Que pasó con esto?

2021-07-17 23:01 UTC, Ballena0 approved these changes

2021-07-17 23:01 UTC, merged