Text to speech
Ballena0/backend-pi-gpi pull request #12
Opened 2021-07-01 14:10 UTC by VRAraya-olx

# Description

Por favor incluye una lista de los cambios. Por favor incluye contexto y motivación relevantes. Si incluyes nuevas dependencias, por favor, haz una lista de las necesarias.

Se implementa función que sintetiza texto a voz a través del API de Google, y se habilita un endpoint para probarlo

## Type of change

- [ ] Bug fix 
- [x] New feature 
- [ ] Breaking change (cambio que puede romper la aplicación)
- [ ] Docs

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

2021-07-04 05:59 UTC, VRAraya commented
Actualización: Se agrega el parametro gender a la funcion y se retorna el archivo de audio codificado en base64 y en formato OGG para ser reproducido de forma nativa en Android.

2021-07-05 01:54 UTC, Ballena0 requested changes
Estás usando una `google cloud app` tuya? para probar con esas credenciales.

2021-07-05 01:54 UTC, Ballena0 commented on apps/transcript/interface.py
> +def text_to_speech(text, language, gender):
Para este caso el output siempre es ingles, por lo que el parametro idioma deberia querdar `language="en-Us"`

2021-07-05 01:54 UTC, Ballena0 commented on apps/transcript/interface.py
> +synthetizeText = Blueprint('synthetizeText', __name__)
usar snake case pls, `synthetize_text`

2021-07-05 01:54 UTC, Ballena0 commented on apps/transcript/interface.py
> +        gender = request.form.get('gender')
No estaremos enviando la data desde un formulario, podriamos usar `request.json.get()` o `request.get_json()`

2021-07-05 01:54 UTC, Ballena0 commented on apps/transcript/interface.py
> +from google.cloud import texttospeech
Esta libreria tiene sus excepciones correspondientes?

2021-07-05 01:54 UTC, Ballena0 commented on apps/transcript/interface.py
> +        return str(e)
Si falla, será muy difícil saber en que parte de todo lo que esta dentro del bloque `try` falla. Sí la librería tiene sus excepciones hay que dividir, todo lo que esta en `try`, en diferentes bloques de `try catch` con sus respectivos manejadores de errores.

2021-07-05 17:39 UTC, Ballena0 commented
> Actualización: Se agrega el parametro gender a la funcion y se retorna el archivo de audio codificado en base64 y en formato OGG para ser reproducido de forma nativa en Android.

@mapacheverdugo @PollitoMayo respecto de esto no hay problemas con los formatos? pregunto para cambiarlo antes de mezclar en caso de ser necesario

2021-07-07 21:56 UTC, mapacheverdugo commented
> > Actualización: Se agrega el parametro gender a la funcion y se retorna el archivo de audio codificado en base64 y en formato OGG para ser reproducido de forma nativa en Android.
> 
> @mapacheverdugo @PollitoMayo respecto de esto no hay problemas con los formatos? pregunto para cambiarlo antes de mezclar en caso de ser necesario

La librería que implementó la @PollitoMayo  es `just_audio`, permite reproducir tanto `.ogg` como `.mp3` (y varios más), así que no hay problema con el formato

Respecto al PR, no lo pude probar porque las `keys.json` de la @mariam6697 no tienen habilitada la API de TTS y creo que el Victor no dejó unas keys por ahí

2021-07-08 03:26 UTC, VRAraya-olx commented
Hice los cambios solicitados, exceptuando por lo de los try catch, dado que no encontré en la documentación de la librería respecto a las Excepciones que puede tener, si alguien las encuentra, agradecería colocarlas, al menos por acá no están: https://cloud.google.com/text-to-speech/docs/getting-support

2021-07-08 03:28 UTC, VRAraya-olx commented
También subí el keys.json para que lo puedan probar

2021-07-11 18:27 UTC, Ballena0 commented
La unica excepción que encontré en la [Documentación](https://googleapis.dev/python/texttospeech/latest/texttospeech_v1/text_to_speech.html) es para el metodo `TextToSpeechClient` al momento de realizar la conexión con la API de Google. Si se conecta de manera correcta el resto de metodos deben funcionar bien. Aquí la [excepción](https://googleapis.dev/python/google-auth/latest/reference/google.auth.exceptions.html#google.auth.exceptions.MutualTLSChannelError)

2021-07-15 18:17 UTC, mapacheverdugo commented on apps/transcript/interface.py
> +            if 'text' in request_data:
Estas lineas no están funcionando bien, si no le mando `language` o `gender`, a la función le entra un `None` y me devuelve el `audio_encoded_base64` como `None`. No creo que sea necesario corregir porque es solo una ruta de prueba que se va a eliminar

2021-07-15 18:19 UTC, mapacheverdugo approved these changes
Encontré un error, pero estaba dentro de la ruta que se va a eliminar, lo dejé anotado para tenerlo en consideración, pero no creo que sea necesaria su corrección para aprobar y fusionar el PR

2021-07-15 20:38 UTC, PollitoMayo approved these changes
Me funciona bien, y el audio es correcto, nomas reiterar lo que comentó Jorge donde si no ingreso `gender` o `language` me devuelve error, pero para efectos del proyecto es algo menor.

2021-07-18 00:14 UTC, Ballena0 approved these changes

2021-07-18 00:16 UTC, merged