Added endpoint to receive audio file
Ballena0/backend-pi-gpi pull request #5
Opened 2021-06-08 23:43 UTC by mariam6697

# Description

Cree un endpoint en la aplicación `recept` que recibe vía HTTP con método POST un archivo etiquetado con `audio` como key en un multipart-form.

## Type of change

- [ ] Bug fix 
- [x] New feature 
- [ ] Breaking change (cambio que puede romper la aplicación)
- [ ] Docs

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

2021-06-08 23:48 UTC, PollitoMayo approved these changes

2021-06-09 15:44 UTC, mapacheverdugo approved these changes
Muy lindo

2021-06-09 16:07 UTC, Ballena0 requested changes
Gran trabajo, solo estos pequeños cambios :)

2021-06-09 16:07 UTC, Ballena0 commented on apps/recept/interface.py
> +        print(audio_file)
pls borrar el print statement

2021-06-09 16:07 UTC, Ballena0 commented on apps/recept/interface.py
> +        return jsonify(status='error')
Cambiar por `except Exception as e` y retornarlo dentro del json bajo la etiqueta de error.
Also usar `jsonify(...), status_code(int)`

2021-06-09 16:07 UTC, Ballena0 commented on apps/recept/interface.py
> +        return jsonify(status='ok')
```suggestion
    try:
        audio_file = request.files['audio']
    return jsonify(status='ok')
```

2021-06-09 16:09 UTC, Ballena0 commented on apps/recept/interface.py
> +        return jsonify(status='ok')
Tambien retornar un `status_code` con `jsonify(...), status_code`

2021-06-09 19:54 UTC, mariam6697 commented on apps/recept/interface.py
> +        return jsonify(status='error')
¿Qué status_code se supone que debería retornar?

2021-06-09 20:00 UTC, mariam6697 commented on apps/recept/interface.py
> +        return jsonify(status='error')
Nmv ya vi que `e.code` funciona

2021-06-10 02:29 UTC, Ballena0 approved these changes
LGTM! wen trabajo :3

2021-06-10 17:18 UTC, merged