Implementando QuickStart de la libreria
Ballena0/backend-pi-gpi pull request #8
Opened 2021-06-16 15:47 UTC by VRAraya

# Description

Por favor incluye una lista de los cambios. Por favor incluye contexto y motivación relevantes. Si incluyes nuevas dependencias, por favor, haz una lista de las necesarias.

* Se sube una primera implementación, favor notar que para que funcione, se necesita descargar un Service Account Client File, el cual se obtiene tras realizar la activación de una cuenta de servicio dentro de la consola de Google Cloud, incluyendo además, que es un servicio de pago.

## Type of change

- [ ] Bug fix 
- [ x] New feature 
- [ ] Breaking change (cambio que puede romper la aplicación)
- [ ] Docs

# Checklist:

- [x] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

2021-06-17 01:41 UTC, Ballena0 commented
¿Cual es package necesario para esto? incluir la dependencia en `requeriments.txt` con el comando `make freeze` (asegurar que se haya ejecutado `make` primero). ¿Cuales son los costos del producto? incluir cualquier recurso que demuestre el valor (links, imagenes, etc). ¿Cuales beneficios otorga este package? ¿Es superior a los demas que se están trabajando?. Incluir `checklist` de los minimos necesarios para continuar con el uso de un package(se pueden encontrar en los otros `pull request` abiertos a la fecha 16/06).

2021-06-17 01:49 UTC, Ballena0 requested changes
Solo tiene un uso, el codigo no es reutilizable. ¿Funciona offline?. Como minimo debería ser una funcion(`def function_name(params): ...`) que reciba por parametro el audio y la configuración sea modificable en diferentes aspectos. Puede ser una clase tambien(POO).

2021-06-17 01:49 UTC, Ballena0 commented on samples/snippets/quickstart.py
> +    language_code="en-US",
¿Es capaz de reconocer otros idiomas?

2021-06-17 01:49 UTC, Ballena0 commented on samples/snippets/quickstart.py
> +gcs_uri = "gs://cloud-samples-data/speech/brooklyn_bridge.raw"
¿Solo reconoce archivos en internet mediante una uri?

2021-06-17 01:49 UTC, Ballena0 commented on samples/snippets/quickstart.py
> +    encoding=speech.RecognitionConfig.AudioEncoding.LINEAR16,
¿Que otros tipos de codificación admite?

2021-06-17 02:03 UTC, Ballena0 commented
Es exactamente lo mismo que está en la documentación de google. [Documentación](https://cloud.google.com/speech-to-text/docs/quickstart-client-libraries#client-libraries-install-python). Cual es el punto que intenta demostrar este pull request? como aporta al proyecto?

2021-07-07 22:43 UTC, mapacheverdugo commented
Esta se cierra en pos del PR #12? @VRAraya  @Ballena0

2021-07-08 03:33 UTC, VRAraya-olx commented
> Esta se cierra en pos del PR #12? @VRAraya @Ballena0

Yo diría que sí xd

2021-07-08 23:12 UTC, closed without merging